project:
  type: website

website:
  title: "My Digital Notebook"
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Blog"
        file: blog.qmd
      #- workshops.qmd
      - text: "Projects"
        file: projects.qmd
      - about.qmd
sidebar:
  - title: "Projects"
    style: "docked"
    background: light
    contents:
      - projects.qmd
      - project-01.qmd
      - project-02.qmd

format:
  html:
    theme: Sandstone
    css: styles.css
    toc: true



