project:
  type: website
  output-dir: docs

website:
  title: "Gabriela Palomo"
  page-navigation: true
  navbar:
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
      - text: "My Digital Notebook"
        file: blog.qmd
      #- workshops.qmd
      - text: "Projects"
        file: projects.qmd
      # - about.qmd
sidebar:
  - title: "Projects"
    style: "docked"
    background: light
    contents:
      - projects.qmd
      - project-01.qmd
      - project-02.qmd

format:
  html:
    theme: Sandstone
    css: css/styles.css
    toc: true



