project:
  type: website

website:
  title: "My Digital Notebook"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      #- workshops.qmd
      - blog.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



